FAIL: test_eager_accuracy (__main__.TestSquareDevelopCase1_FP16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_silu_develop.py", line 178, in test_eager_accuracy
    api="paddle.nn.functional.silu",
  File "../utils.py", line 75, in np_assert_accuracy
    value_b=str(np_b.flatten()[max_rtol_idx].item()),
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001
paddle.nn.functional.silu eager backward: compare paddle_develop res with torch failed in float16 dtype,
max_atol_idx: 891446, paddle_develop_value: -0.267822265625, torch_value: -0.267578125,
max_rtol_idx: 5214953, paddle_develop_value: 0.0, torch_value: 0.0,

Mismatched elements: 380 / 22413312 (0.0017%)
Max absolute difference: 0.0002441
Max relative difference: 0.0009727
 x: array([[[-0.0682  ,  0.0453  ,  0.11536 , ..., -0.0187  , -0.0426  ,
         -0.1425  ]],
...
 y: array([[[-0.0682  ,  0.0453  ,  0.11536 , ..., -0.0187  , -0.0426  ,
         -0.1425  ]],
...

======================================================================
FAIL: test_static_accuracy (__main__.TestSquareDevelopCase1_FP16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_silu_develop.py", line 227, in test_static_accuracy
    api="paddle.nn.functional.silu",
  File "../utils.py", line 75, in np_assert_accuracy
    value_b=str(np_b.flatten()[max_rtol_idx].item()),
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001
paddle.nn.functional.silu static backward: compare paddle_develop res with torch failed in float16 dtype,
max_atol_idx: 59443, paddle_develop_value: -0.26953125, torch_value: -0.269287109375,
max_rtol_idx: 6696278, paddle_develop_value: 0.0, torch_value: 0.0,

Mismatched elements: 350 / 22413312 (0.00156%)
Max absolute difference: 0.0002441
Max relative difference: 0.0009737
 x: array([[[-0.1475  ,  0.05704 , -0.1532  , ...,  0.1667  , -0.185   ,
         -0.1832  ]],
...
 y: array([[[-0.1475  ,  0.05704 , -0.1532  , ...,  0.1667  , -0.185   ,
         -0.1832  ]],
...

======================================================================
FAIL: test_eager_accuracy (__main__.TestSquareDevelopCase2_FP16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_silu_develop.py", line 178, in test_eager_accuracy
    api="paddle.nn.functional.silu",
  File "../utils.py", line 75, in np_assert_accuracy
    value_b=str(np_b.flatten()[max_rtol_idx].item()),
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001
paddle.nn.functional.silu eager backward: compare paddle_develop res with torch failed in float16 dtype,
max_atol_idx: 43478, paddle_develop_value: -0.283203125, torch_value: -0.283447265625,
max_rtol_idx: 614962, paddle_develop_value: 0.0, torch_value: 0.0,

Mismatched elements: 125 / 8388608 (0.00149%)
Max absolute difference: 0.0002441
Max relative difference: 0.000972
 x: array([[-0.01342,  0.01787,  0.1876 , ...,  0.2695 ,  0.156  ,  0.0824 ],
       [ 0.1335 , -0.03238, -0.1962 , ...,  0.01602,  0.03574, -0.2065 ],
       [-0.12354,  0.1776 , -0.2263 , ..., -0.3584 ,  0.0483 , -0.2051 ],...
 y: array([[-0.01342,  0.01787,  0.1876 , ...,  0.2695 ,  0.156  ,  0.0824 ],
       [ 0.1335 , -0.03238, -0.1962 , ...,  0.01602,  0.03574, -0.2065 ],
       [-0.12354,  0.1776 , -0.2263 , ..., -0.3584 ,  0.0483 , -0.2051 ],...

======================================================================
FAIL: test_static_accuracy (__main__.TestSquareDevelopCase2_FP16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_silu_develop.py", line 227, in test_static_accuracy
    api="paddle.nn.functional.silu",
  File "../utils.py", line 75, in np_assert_accuracy
    value_b=str(np_b.flatten()[max_rtol_idx].item()),
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001
paddle.nn.functional.silu static backward: compare paddle_develop res with torch failed in float16 dtype,
max_atol_idx: 1009534, paddle_develop_value: 0.299560546875, torch_value: 0.2998046875,
max_rtol_idx: 2320726, paddle_develop_value: 0.0, torch_value: 0.0,

Mismatched elements: 150 / 8388608 (0.00179%)
Max absolute difference: 0.0002441
Max relative difference: 0.000972
 x: array([[ 0.1344  ,  0.07214 ,  0.07    , ...,  0.0678  , -0.0814  ,
        -0.02151 ],
       [ 0.013885, -0.1166  ,  0.1382  , ...,  0.05347 ,  0.1097  ,...
 y: array([[ 0.1344  ,  0.07214 ,  0.07    , ...,  0.0678  , -0.0814  ,
        -0.02151 ],
       [ 0.013885, -0.1166  ,  0.1382  , ...,  0.05347 ,  0.1097  ,...

----------------------------------------------------------------------
Ran 24 tests in 1355.366s

FAILED (failures=4)
